In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [32]:
import pandas as pd

df = pd.read_csv("../DATASETS/DIABETES_DATA/diabetes_dataset.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [33]:
print(df.shape)
print(df.columns)
df.info()

(768, 9)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [34]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [35]:
zero_cols = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

for col in zero_cols:
    print(col, ":", (df[col] == 0).sum())

Glucose : 5
BloodPressure : 35
SkinThickness : 227
Insulin : 374
BMI : 11

In [36]:
df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [37]:
import numpy as np

zero_cols = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

df[zero_cols] = df[zero_cols].replace(0, np.nan)

In [38]:
for col in zero_cols:
    df[col].fillna(df[col].median(), inplace=True)

/var/folders/yx/53kdbhgn4dx425n_l9dqv9500000gn/T/ipykernel_9132/990249551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/yx/53kdbhgn4dx425n_l9dqv9500000gn/T/ipykernel_9132/990249551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/yx/53kdbhgn4dx425n_l9dqv9500000gn/T/ipykernel_9132/990249551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/yx/53kdbhgn4dx425n_l9dqv9500000gn/T/ipykernel_9132/990249551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/var/folders/yx/53kdbhgn4dx425n_l9dqv9500000gn/T/ipykernel_9132/990249551.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [39]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [40]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [41]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [43]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: divide by zero encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: overflow encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/linear_model/_linear_loss.py:330: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

LogisticRegression(max_iter=1000)

In [45]:
y_pred = log_model.predict(X_test_scaled)

/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [46]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, log_model.predict_proba(X_test_scaled)[:,1]))

[[82 18]
 [27 27]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154

ROC-AUC: 0.812962962962963

/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [47]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)  # no scaling needed for RF

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=42)

In [48]:
y_pred_rf = rf_model.predict(X_test)

In [49]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, rf_model.predict_proba(X_test)[:,1]))

[[83 17]
 [25 29]]
              precision    recall  f1-score   support

           0       0.77      0.83      0.80       100
           1       0.63      0.54      0.58        54

    accuracy                           0.73       154
   macro avg       0.70      0.68      0.69       154
weighted avg       0.72      0.73      0.72       154

ROC-AUC: 0.8131481481481481

In [50]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred_rf)
print("Accuracy:", accuracy)

Accuracy: 0.7272727272727273

In [51]:
from sklearn.metrics import accuracy_score

acc_log = accuracy_score(y_test, y_pred)
print("Logistic Regression Accuracy:", acc_log)

Logistic Regression Accuracy: 0.7077922077922078

In [22]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (0.12.4)
Requirement already satisfied: numpy>=1.17.3 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy>=1.5.0 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from imbalanced-learn) (3.6.0)

In [52]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

/Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(

In [53]:
rf_smote = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

rf_smote.fit(X_res, y_res)

y_pred_smote = rf_smote.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score

print(confusion_matrix(y_test, y_pred_smote))
print(classification_report(y_test, y_pred_smote))
print("Accuracy:", accuracy_score(y_test, y_pred_smote))
print("ROC-AUC:", roc_auc_score(y_test, rf_smote.predict_proba(X_test)[:,1]))

[[78 22]
 [19 35]]
              precision    recall  f1-score   support

           0       0.80      0.78      0.79       100
           1       0.61      0.65      0.63        54

    accuracy                           0.73       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.74      0.73      0.74       154

Accuracy: 0.7337662337662337
ROC-AUC: 0.8178703703703704

In [25]:
pip install xgboost

Requirement already satisfied: xgboost in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (2.1.4)
Requirement already satisfied: numpy in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in /Users/abrarfarhann/CODING/main project sub /.venv/lib/python3.9/site-packages (from xgboost) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

In [54]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    eval_metric="logloss"
)

xgb_model.fit(X_res, y_res)

y_pred_xgb = xgb_model.predict(X_test)

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, xgb_model.predict_proba(X_test)[:,1]))

[[75 25]
 [15 39]]
              precision    recall  f1-score   support

           0       0.83      0.75      0.79       100
           1       0.61      0.72      0.66        54

    accuracy                           0.74       154
   macro avg       0.72      0.74      0.73       154
weighted avg       0.75      0.74      0.74       154

Accuracy: 0.7402597402597403
ROC-AUC: 0.8244444444444444

In [55]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    "n_estimators": [200,300,400],
    "max_depth": [None,5,10,15],
    "min_samples_split": [2,5,10]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(rf, param_grid, cv=5, scoring="roc_auc")
grid.fit(X_res, y_res)

best_rf = grid.best_estimator_

y_pred_best = best_rf.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

print("Accuracy:", accuracy_score(y_test, y_pred_best))
print(classification_report(y_test, y_pred_best))
print("ROC-AUC:", roc_auc_score(y_test, best_rf.predict_proba(X_test)[:,1]))

KeyboardInterrupt:

In [56]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss"
)

xgb.fit(X_res, y_res)

y_pred_xgb = xgb.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, xgb.predict_proba(X_test)[:,1]))

Accuracy: 0.7532467532467533
              precision    recall  f1-score   support

           0       0.83      0.78      0.80       100
           1       0.63      0.70      0.67        54

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.74       154
weighted avg       0.76      0.75      0.76       154

ROC-AUC: 0.8172222222222222

In [57]:
import joblib
joblib.dump(xgb, "diabetes_model.pkl")

['diabetes_model.pkl']

In [30]:
joblib.dump(X_res.columns.tolist(), "diabetes_features.pkl")

['diabetes_features.pkl']

In [31]:
joblib.dump(scaler, "diabetes_scaler.pkl")

['diabetes_scaler.pkl']

In [64]:
def diabetes_risk_level(prob):
    """Map diabetes risk probability (0-1) to a categorical level."""
    # Adjusted thresholds based on model behavior:
    # - LOW: prob < 0.008
    # - MEDIUM: 0.008 <= prob < 0.012
    # - HIGH: prob >= 0.012
    if prob >= 0.012:
        return "HIGH"
    elif prob >= 0.008:
        return "MEDIUM"
    else:
        return "LOW"

# Example usage (after computing y_prob = model.predict_proba(... )[:, 1]):
# diabetes_risk_labels = [diabetes_risk_level(p) for p in y_prob]

In [59]:
import joblib
import pandas as pd

# Load saved diabetes model artifacts
diab_model = joblib.load("diabetes_model.pkl")
diab_scaler = joblib.load("diabetes_scaler.pkl")
diab_features = joblib.load("diabetes_features.pkl")

print("Diabetes model expects features (in order):")
print(diab_features)

# To predict for a new patient, create a dict with ALL these keys.
# Example (fill with real values):

# new_patient = {
#     "Pregnancies": 2,
#     "Glucose": 120,
#     ...  # one entry for each feature in diab_features
# }

# Then run:

# X_new = pd.DataFrame([new_patient])[diab_features]
# X_new_scaled = diab_scaler.transform(X_new)
# prob = diab_model.predict_proba(X_new_scaled)[:, 1][0]
# level = diabetes_risk_level(prob)
# print("Diabetes risk probability:", prob)
# print("Diabetes risk level:", level)

Diabetes model expects features (in order):
['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [65]:
import joblib
import pandas as pd

# Load saved diabetes model artifacts
diab_model = joblib.load("diabetes_model.pkl")
diab_scaler = joblib.load("diabetes_scaler.pkl")
diab_features = joblib.load("diabetes_features.pkl")

print("Diabetes model expects features (in order):")
print(diab_features)

# Example 1: likely LOW diabetes risk
new_patient_low = {
    "Pregnancies": 1,
    "Glucose": 95,
    "BloodPressure": 70,
    "SkinThickness": 20,
    "Insulin": 80,
    "BMI": 24.0,
    "DiabetesPedigreeFunction": 0.30,
    "Age": 30,
}

X_low = pd.DataFrame([new_patient_low])[diab_features]
X_low_scaled = diab_scaler.transform(X_low)
prob_low = diab_model.predict_proba(X_low_scaled)[:, 1][0]
level_low = diabetes_risk_level(prob_low)

print("\nLOW-RISK example:")
print("Diabetes risk probability:", prob_low)
print("Diabetes risk level:", level_low)

Diabetes model expects features (in order):
['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

LOW-RISK example:
Diabetes risk probability: 0.00410712
Diabetes risk level: LOW

In [75]:
# Example 2: likely HIGH diabetes risk
new_patient_high = {
    "Pregnancies": 10,
    "Glucose": 230,
    "BloodPressure": 100,
    "SkinThickness": 45,
    "Insulin": 400,
    "BMI": 45.0,
    "DiabetesPedigreeFunction": 1.20,
    "Age": 65,
}

X_high = pd.DataFrame([new_patient_high])[diab_features]
X_high_scaled = diab_scaler.transform(X_high)
prob_high = diab_model.predict_proba(X_high_scaled)[:, 1][0]
level_high = diabetes_risk_level(prob_high)

print("\nHIGH-RISK example:")
print("Diabetes risk probability:", prob_high)
print("Diabetes risk level:", level_high)

HIGH-RISK example:
Diabetes risk probability: 0.014110581
Diabetes risk level: HIGH

In [70]:
# Example 3: MEDIUM diabetes risk (based on a real patient)
new_patient_medium = {
    "Pregnancies": 8,
    "Glucose": 183,
    "BloodPressure": 64,
    "SkinThickness": 29,
    "Insulin": 125,
    "BMI": 23.3,
    "DiabetesPedigreeFunction": 0.672,
    "Age": 32,
}

X_med = pd.DataFrame([new_patient_medium])[diab_features]
X_med_scaled = diab_scaler.transform(X_med)
prob_med = diab_model.predict_proba(X_med_scaled)[:, 1][0]
level_med = diabetes_risk_level(prob_med)

print("\nMEDIUM-RISK example:")
print("Diabetes risk probability:", prob_med)
print("Diabetes risk level:", level_med)

MEDIUM-RISK example:
Diabetes risk probability: 0.008740466
Diabetes risk level: MEDIUM

In [69]:
# Helper: find a real patient with MEDIUM diabetes risk probability
import numpy as np

X_all = df[diab_features]
X_all_scaled = diab_scaler.transform(X_all)
probs_all = diab_model.predict_proba(X_all_scaled)[:, 1]

mask = (probs_all >= 0.008) & (probs_all < 0.012)
indices = np.where(mask)[0]
print("Found", len(indices), "rows in MEDIUM band [0.008, 0.012)")
if len(indices) > 0:
    i = int(indices[0])
    print("Chosen row index:", i)
    print("Probability:", float(probs_all[i]))
    print("Features dict:", X_all.iloc[i].to_dict())
else:
    print("No rows found in the specified probability band.")

Found 41 rows in MEDIUM band [0.008, 0.012)
Chosen row index: 2
Probability: 0.008740466088056564
Features dict: {'Pregnancies': 8.0, 'Glucose': 183.0, 'BloodPressure': 64.0, 'SkinThickness': 29.0, 'Insulin': 125.0, 'BMI': 23.3, 'DiabetesPedigreeFunction': 0.672, 'Age': 32.0}

In [73]:
# Example 4: another MEDIUM diabetes risk (auto-selected from dataset)
import numpy as np

X_all = df[diab_features]
X_all_scaled = diab_scaler.transform(X_all)
probs_all = diab_model.predict_proba(X_all_scaled)[:, 1]

mask_med = (probs_all >= 0.008) & (probs_all < 0.012)
indices_med = np.where(mask_med)[0]
print("Found", len(indices_med), "MEDIUM-band rows [0.008, 0.012)")

if len(indices_med) > 1:
    i_med2 = int(indices_med[1])
elif len(indices_med) > 0:
    i_med2 = int(indices_med[0])
    print("Only one MEDIUM-band row available; reusing it.")
else:
    raise ValueError("No rows found in MEDIUM probability band; adjust thresholds or retrain model.")

row_med2 = X_all.iloc[i_med2]
new_patient_medium2 = row_med2.to_dict()

X_med2 = pd.DataFrame([new_patient_medium2])[diab_features]
X_med2_scaled = diab_scaler.transform(X_med2)
prob_med2 = diab_model.predict_proba(X_med2_scaled)[:, 1][0]
level_med2 = diabetes_risk_level(prob_med2)

print("\nMEDIUM-RISK example 2:")
print("Diabetes risk probability:", prob_med2)
print("Diabetes risk level:", level_med2)
print("Features:", new_patient_medium2)

Found 41 MEDIUM-band rows [0.008, 0.012)

MEDIUM-RISK example 2:
Diabetes risk probability: 0.008740466
Diabetes risk level: MEDIUM
Features: {'Pregnancies': 9.0, 'Glucose': 102.0, 'BloodPressure': 76.0, 'SkinThickness': 37.0, 'Insulin': 125.0, 'BMI': 32.9, 'DiabetesPedigreeFunction': 0.665, 'Age': 46.0}

In [74]:
# Example 5: another HIGH diabetes risk (auto-selected from dataset)
import numpy as np

X_all = df[diab_features]
X_all_scaled = diab_scaler.transform(X_all)
probs_all = diab_model.predict_proba(X_all_scaled)[:, 1]

mask_high = (probs_all >= 0.012)
indices_high = np.where(mask_high)[0]
print("Found", len(indices_high), "HIGH-band rows [0.012, 1.0]")

if len(indices_high) > 1:
    i_high2 = int(indices_high[1])
elif len(indices_high) > 0:
    i_high2 = int(indices_high[0])
    print("Only one HIGH-band row available; reusing it.")
else:
    raise ValueError("No rows found in HIGH probability band; adjust thresholds or retrain model.")

row_high2 = X_all.iloc[i_high2]
new_patient_high2 = row_high2.to_dict()

X_high2 = pd.DataFrame([new_patient_high2])[diab_features]
X_high2_scaled = diab_scaler.transform(X_high2)
prob_high2 = diab_model.predict_proba(X_high2_scaled)[:, 1][0]
level_high2 = diabetes_risk_level(prob_high2)

print("\nHIGH-RISK example 2:")
print("Diabetes risk probability:", prob_high2)
print("Diabetes risk level:", level_high2)
print("Features:", new_patient_high2)

Found 149 HIGH-band rows [0.012, 1.0]

HIGH-RISK example 2:
Diabetes risk probability: 0.014110581
Diabetes risk level: HIGH
Features: {'Pregnancies': 10.0, 'Glucose': 139.0, 'BloodPressure': 80.0, 'SkinThickness': 29.0, 'Insulin': 125.0, 'BMI': 27.1, 'DiabetesPedigreeFunction': 1.441, 'Age': 57.0}

In [76]:
# Find LOW and HIGH risk examples with Pregnancies = 0
import numpy as np

# Filter to rows with Pregnancies == 0
mask_p0 = df["Pregnancies"] == 0
X_p0 = df.loc[mask_p0, diab_features]

# Compute probabilities for these rows
X_p0_scaled = diab_scaler.transform(X_p0)
probs_p0 = diab_model.predict_proba(X_p0_scaled)[:, 1]

print("Total rows with Pregnancies = 0:", X_p0.shape[0])

# Find index of lowest and highest probability within Pregnancies = 0 subset
if X_p0.shape[0] > 0:
    # Indices relative to the original dataframe
    orig_indices_p0 = X_p0.index.to_numpy()
    i_low_local = int(np.argmin(probs_p0))
    i_high_local = int(np.argmax(probs_p0))
    i_low_p0 = int(orig_indices_p0[i_low_local])
    i_high_p0 = int(orig_indices_p0[i_high_local])
    
    row_low_p0 = df.loc[i_low_p0, diab_features]
    row_high_p0 = df.loc[i_high_p0, diab_features]
    
    # Build dicts
    new_patient_low_p0 = row_low_p0.to_dict()
    new_patient_high_p0 = row_high_p0.to_dict()
    
    # Recompute probabilities and levels for clarity
    X_low_p0 = pd.DataFrame([new_patient_low_p0])[diab_features]
    X_low_p0_scaled = diab_scaler.transform(X_low_p0)
    prob_low_p0 = diab_model.predict_proba(X_low_p0_scaled)[:, 1][0]
    level_low_p0 = diabetes_risk_level(prob_low_p0)
    
    X_high_p0 = pd.DataFrame([new_patient_high_p0])[diab_features]
    X_high_p0_scaled = diab_scaler.transform(X_high_p0)
    prob_high_p0 = diab_model.predict_proba(X_high_p0_scaled)[:, 1][0]
    level_high_p0 = diabetes_risk_level(prob_high_p0)
    
    print("\nLOW-RISK (Pregnancies=0) example:")
    print("Diabetes risk probability:", float(prob_low_p0))
    print("Diabetes risk level:", level_low_p0)
    print("Features:", new_patient_low_p0)
    
    print("\nHIGH-RISK (Pregnancies=0) example:")
    print("Diabetes risk probability:", float(prob_high_p0))
    print("Diabetes risk level:", level_high_p0)
    print("Features:", new_patient_high_p0)
else:
    print("No rows with Pregnancies = 0 found in dataset.")

Total rows with Pregnancies = 0: 111

LOW-RISK (Pregnancies=0) example:
Diabetes risk probability: 0.004107119981199503
Diabetes risk level: LOW
Features: {'Pregnancies': 0.0, 'Glucose': 105.0, 'BloodPressure': 64.0, 'SkinThickness': 41.0, 'Insulin': 142.0, 'BMI': 41.5, 'DiabetesPedigreeFunction': 0.173, 'Age': 22.0}

HIGH-RISK (Pregnancies=0) example:
Diabetes risk probability: 0.02943776547908783
Diabetes risk level: HIGH
Features: {'Pregnancies': 0.0, 'Glucose': 138.0, 'BloodPressure': 72.0, 'SkinThickness': 29.0, 'Insulin': 125.0, 'BMI': 36.3, 'DiabetesPedigreeFunction': 0.933, 'Age': 25.0}

In [77]:
# Synthetic outside data: Pregnancies = 0 (one LOW, one HIGH)
# These examples are NOT taken from the training dataset.
import pandas as pd

# Synthetic LOW-risk patient (Pregnancies = 0)
new_patient_low_outside = {
    "Pregnancies": 0,
    "Glucose": 92,
    "BloodPressure": 70,
    "SkinThickness": 24,
    "Insulin": 80,
    "BMI": 23.5,
    "DiabetesPedigreeFunction": 0.15,
    "Age": 24,
}

# Synthetic HIGH-risk patient (Pregnancies = 0)
new_patient_high_outside = {
    "Pregnancies": 0,
    "Glucose": 210,
    "BloodPressure": 88,
    "SkinThickness": 35,
    "Insulin": 220,
    "BMI": 38.0,
    "DiabetesPedigreeFunction": 1.20,
    "Age": 55,
}

# Evaluate both with the trained model
X_low_out = pd.DataFrame([new_patient_low_outside])[diab_features]
X_low_out_scaled = diab_scaler.transform(X_low_out)
prob_low_out = diab_model.predict_proba(X_low_out_scaled)[:, 1][0]
level_low_out = diabetes_risk_level(prob_low_out)

X_high_out = pd.DataFrame([new_patient_high_outside])[diab_features]
X_high_out_scaled = diab_scaler.transform(X_high_out)
prob_high_out = diab_model.predict_proba(X_high_out_scaled)[:, 1][0]
level_high_out = diabetes_risk_level(prob_high_out)

print("Synthetic LOW-RISK (Pregnancies=0, outside data):")
print("Diabetes risk probability:", float(prob_low_out))
print("Diabetes risk level:", level_low_out)
print("Features:", new_patient_low_outside)

print("\nSynthetic HIGH-RISK (Pregnancies=0, outside data):")
print("Diabetes risk probability:", float(prob_high_out))
print("Diabetes risk level:", level_high_out)
print("Features:", new_patient_high_outside)

Synthetic LOW-RISK (Pregnancies=0, outside data):
Diabetes risk probability: 0.004107119981199503
Diabetes risk level: LOW
Features: {'Pregnancies': 0, 'Glucose': 92, 'BloodPressure': 70, 'SkinThickness': 24, 'Insulin': 80, 'BMI': 23.5, 'DiabetesPedigreeFunction': 0.15, 'Age': 24}

Synthetic HIGH-RISK (Pregnancies=0, outside data):
Diabetes risk probability: 0.014794794842600822
Diabetes risk level: HIGH
Features: {'Pregnancies': 0, 'Glucose': 210, 'BloodPressure': 88, 'SkinThickness': 35, 'Insulin': 220, 'BMI': 38.0, 'DiabetesPedigreeFunction': 1.2, 'Age': 55}